# Travis-CI integration for pidgen

dist: xenial

language: python

python:
  - 3.7

before_install:
  - sudo apt-get install python-pip python-coverage

install:
  - pip install -r requirements.txt
  - pip install wheel

script:
  # Check code style
  - flake8 .
  # Ensure that the script at least runs (display help information)
  - python -m pidgen -h
  # Show version information
  - python -m pidgen --version
  # Test that the package can be installed OK
  - python setup.py bdist_wheel --universal
  # TODO - Run coverage tests

after_success:
  - coveralls