# Travis-CI integration for PyGen

dist: xenial

language: python

python:
  - 2.7
  - 3.7

before_install:
  - sudo apt-get install python3-pip python3-coverage

install:
  - pip install -r requirements.txt

script:
  # Check code style
  - flake8 .
  # Ensure that the script at least runs (display help information)
  - python -m PyGen -h
  # Show version information
  - python -m PyGen --version
  # TODO - Run coverage tests

after_success:
  - coveralls